import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    // backend/ and scripts/ are linted below. supabase/functions is Deno with a
    // different global set and its own type resolution, so it stays out.
    ignores: [
      "dist",
      ".output",
      ".vinxi",
      "**/node_modules/**",
      "admin-portal",
      "supabase/functions",
      // Generated by `supabase gen types typescript --linked`. Regenerating it
      // would otherwise reintroduce thousands of prettier diffs.
      "src/lib/database.types.ts",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["src/**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "server-only",
              message:
                "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
            },
          ],
        },
      ],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
  {
    /**
     * The ratchet.
     *
     * `no-explicit-any` stays off across `src/` — there are ~950 occurrences and
     * turning it on globally would just get turned back off. Scoped here it is
     * enforceable today.
     *
     * `explicit-module-boundary-types` is the more valuable of the two: every
     * FUTURE export from api.ts must declare its return type. Without it the
     * next hurried change adds an untyped function and the field-name drift that
     * broke consent revoke, the vaccines page and the Rehab tab starts again.
     *
     * Both rules are syntactic, so no type-aware linting and no CI slowdown.
     * They must be `error`, not `warn` — `lint:ci` runs `--max-warnings 40`.
     */
    files: ["src/lib/types/**/*.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/explicit-module-boundary-types": "error",
    },
  },
  {
    // Node-side code: seed scripts, verification scripts and the test suite.
    // These were previously unlinted entirely.
    extends: [js.configs.recommended],
    files: ["backend/**/*.{js,mjs}", "scripts/**/*.{js,mjs}"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      // Browser globals too: Puppeteer's page.evaluate() callbacks are serialised
      // and run inside Chrome, so `document` and `location` are legitimately in
      // scope there even though the file itself is Node.
      globals: { ...globals.node, ...globals.browser },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-empty": ["error", { allowEmptyCatch: true }],
    },
  },
  eslintPluginPrettier,
);
