/* eslint-disable */
/**
 * Generated API helpers.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.40.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

export const api: any = {
  records: {
    getDIDs: "records:getDIDs",
    getCredentials: "records:getCredentials",
    getPatients: "records:getPatients",
    getStaff: "records:getStaff",
    updatePatientVitals: "records:updatePatientVitals",
    updateStaffLocation: "records:updateStaffLocation",
  }
};
