/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as HyperledgerRouteImport } from './routes/hyperledger'
import { Route as FraudRouteImport } from './routes/fraud'
import { Route as FinancialRouteImport } from './routes/financial'
import { Route as FederationRouteImport } from './routes/federation'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as DidsRouteImport } from './routes/dids'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CommandRouteImport } from './routes/command'
import { Route as ChaincodeRouteImport } from './routes/chaincode'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as IndexRouteImport } from './routes/index'

const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const HyperledgerRoute = HyperledgerRouteImport.update({
  id: '/hyperledger',
  path: '/hyperledger',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudRoute = FraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialRoute = FinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const FederationRoute = FederationRouteImport.update({
  id: '/federation',
  path: '/federation',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const DidsRoute = DidsRouteImport.update({
  id: '/dids',
  path: '/dids',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaincodeRoute = ChaincodeRouteImport.update({
  id: '/chaincode',
  path: '/chaincode',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/audit': typeof AuditRoute
  '/chaincode': typeof ChaincodeRoute
  '/command': typeof CommandRoute
  '/compliance': typeof ComplianceRoute
  '/credentials': typeof CredentialsRoute
  '/dids': typeof DidsRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/federation': typeof FederationRoute
  '/financial': typeof FinancialRoute
  '/fraud': typeof FraudRoute
  '/hyperledger': typeof HyperledgerRoute
  '/infrastructure': typeof InfrastructureRoute
  '/login': typeof LoginRoute
  '/people': typeof PeopleRoute
  '/policies': typeof PoliciesRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/audit': typeof AuditRoute
  '/chaincode': typeof ChaincodeRoute
  '/command': typeof CommandRoute
  '/compliance': typeof ComplianceRoute
  '/credentials': typeof CredentialsRoute
  '/dids': typeof DidsRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/federation': typeof FederationRoute
  '/financial': typeof FinancialRoute
  '/fraud': typeof FraudRoute
  '/hyperledger': typeof HyperledgerRoute
  '/infrastructure': typeof InfrastructureRoute
  '/login': typeof LoginRoute
  '/people': typeof PeopleRoute
  '/policies': typeof PoliciesRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/audit': typeof AuditRoute
  '/chaincode': typeof ChaincodeRoute
  '/command': typeof CommandRoute
  '/compliance': typeof ComplianceRoute
  '/credentials': typeof CredentialsRoute
  '/dids': typeof DidsRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/federation': typeof FederationRoute
  '/financial': typeof FinancialRoute
  '/fraud': typeof FraudRoute
  '/hyperledger': typeof HyperledgerRoute
  '/infrastructure': typeof InfrastructureRoute
  '/login': typeof LoginRoute
  '/people': typeof PeopleRoute
  '/policies': typeof PoliciesRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/audit'
    | '/chaincode'
    | '/command'
    | '/compliance'
    | '/credentials'
    | '/dids'
    | '/digital-twin'
    | '/federation'
    | '/financial'
    | '/fraud'
    | '/hyperledger'
    | '/infrastructure'
    | '/login'
    | '/people'
    | '/policies'
    | '/profile'
    | '/resources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/audit'
    | '/chaincode'
    | '/command'
    | '/compliance'
    | '/credentials'
    | '/dids'
    | '/digital-twin'
    | '/federation'
    | '/financial'
    | '/fraud'
    | '/hyperledger'
    | '/infrastructure'
    | '/login'
    | '/people'
    | '/policies'
    | '/profile'
    | '/resources'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/audit'
    | '/chaincode'
    | '/command'
    | '/compliance'
    | '/credentials'
    | '/dids'
    | '/digital-twin'
    | '/federation'
    | '/financial'
    | '/fraud'
    | '/hyperledger'
    | '/infrastructure'
    | '/login'
    | '/people'
    | '/policies'
    | '/profile'
    | '/resources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  AuditRoute: typeof AuditRoute
  ChaincodeRoute: typeof ChaincodeRoute
  CommandRoute: typeof CommandRoute
  ComplianceRoute: typeof ComplianceRoute
  CredentialsRoute: typeof CredentialsRoute
  DidsRoute: typeof DidsRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  FederationRoute: typeof FederationRoute
  FinancialRoute: typeof FinancialRoute
  FraudRoute: typeof FraudRoute
  HyperledgerRoute: typeof HyperledgerRoute
  InfrastructureRoute: typeof InfrastructureRoute
  LoginRoute: typeof LoginRoute
  PeopleRoute: typeof PeopleRoute
  PoliciesRoute: typeof PoliciesRoute
  ProfileRoute: typeof ProfileRoute
  ResourcesRoute: typeof ResourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hyperledger': {
      id: '/hyperledger'
      path: '/hyperledger'
      fullPath: '/hyperledger'
      preLoaderRoute: typeof HyperledgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud': {
      id: '/fraud'
      path: '/fraud'
      fullPath: '/fraud'
      preLoaderRoute: typeof FraudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial': {
      id: '/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof FinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/federation': {
      id: '/federation'
      path: '/federation'
      fullPath: '/federation'
      preLoaderRoute: typeof FederationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dids': {
      id: '/dids'
      path: '/dids'
      fullPath: '/dids'
      preLoaderRoute: typeof DidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chaincode': {
      id: '/chaincode'
      path: '/chaincode'
      fullPath: '/chaincode'
      preLoaderRoute: typeof ChaincodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  AuditRoute: AuditRoute,
  ChaincodeRoute: ChaincodeRoute,
  CommandRoute: CommandRoute,
  ComplianceRoute: ComplianceRoute,
  CredentialsRoute: CredentialsRoute,
  DidsRoute: DidsRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  FederationRoute: FederationRoute,
  FinancialRoute: FinancialRoute,
  FraudRoute: FraudRoute,
  HyperledgerRoute: HyperledgerRoute,
  InfrastructureRoute: InfrastructureRoute,
  LoginRoute: LoginRoute,
  PeopleRoute: PeopleRoute,
  PoliciesRoute: PoliciesRoute,
  ProfileRoute: ProfileRoute,
  ResourcesRoute: ResourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
