/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrescriptionsRouteImport } from './routes/prescriptions'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as NfcCardsRouteImport } from './routes/nfc-cards'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FraudRouteImport } from './routes/fraud'
import { Route as FinancialRouteImport } from './routes/financial'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as DidsRouteImport } from './routes/dids'
import { Route as DidExplorerRouteImport } from './routes/did-explorer'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as CommandRouteImport } from './routes/command'
import { Route as AuditTimelineRouteImport } from './routes/audit-timeline'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsRoute = PrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const NfcCardsRoute = NfcCardsRouteImport.update({
  id: '/nfc-cards',
  path: '/nfc-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudRoute = FraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialRoute = FinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const DidsRoute = DidsRouteImport.update({
  id: '/dids',
  path: '/dids',
  getParentRoute: () => rootRouteImport,
} as any)
const DidExplorerRoute = DidExplorerRouteImport.update({
  id: '/did-explorer',
  path: '/did-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditTimelineRoute = AuditTimelineRouteImport.update({
  id: '/audit-timeline',
  path: '/audit-timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/audit-timeline': typeof AuditTimelineRoute
  '/command': typeof CommandRoute
  '/credentials': typeof CredentialsRoute
  '/did-explorer': typeof DidExplorerRoute
  '/dids': typeof DidsRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/financial': typeof FinancialRoute
  '/fraud': typeof FraudRoute
  '/login': typeof LoginRoute
  '/nfc-cards': typeof NfcCardsRoute
  '/people': typeof PeopleRoute
  '/policies': typeof PoliciesRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/audit-timeline': typeof AuditTimelineRoute
  '/command': typeof CommandRoute
  '/credentials': typeof CredentialsRoute
  '/did-explorer': typeof DidExplorerRoute
  '/dids': typeof DidsRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/financial': typeof FinancialRoute
  '/fraud': typeof FraudRoute
  '/login': typeof LoginRoute
  '/nfc-cards': typeof NfcCardsRoute
  '/people': typeof PeopleRoute
  '/policies': typeof PoliciesRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/audit-timeline': typeof AuditTimelineRoute
  '/command': typeof CommandRoute
  '/credentials': typeof CredentialsRoute
  '/did-explorer': typeof DidExplorerRoute
  '/dids': typeof DidsRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/financial': typeof FinancialRoute
  '/fraud': typeof FraudRoute
  '/login': typeof LoginRoute
  '/nfc-cards': typeof NfcCardsRoute
  '/people': typeof PeopleRoute
  '/policies': typeof PoliciesRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/profile': typeof ProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/audit-timeline'
    | '/command'
    | '/credentials'
    | '/did-explorer'
    | '/dids'
    | '/digital-twin'
    | '/financial'
    | '/fraud'
    | '/login'
    | '/nfc-cards'
    | '/people'
    | '/policies'
    | '/prescriptions'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/audit-timeline'
    | '/command'
    | '/credentials'
    | '/did-explorer'
    | '/dids'
    | '/digital-twin'
    | '/financial'
    | '/fraud'
    | '/login'
    | '/nfc-cards'
    | '/people'
    | '/policies'
    | '/prescriptions'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/audit-timeline'
    | '/command'
    | '/credentials'
    | '/did-explorer'
    | '/dids'
    | '/digital-twin'
    | '/financial'
    | '/fraud'
    | '/login'
    | '/nfc-cards'
    | '/people'
    | '/policies'
    | '/prescriptions'
    | '/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  AuditTimelineRoute: typeof AuditTimelineRoute
  CommandRoute: typeof CommandRoute
  CredentialsRoute: typeof CredentialsRoute
  DidExplorerRoute: typeof DidExplorerRoute
  DidsRoute: typeof DidsRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  FinancialRoute: typeof FinancialRoute
  FraudRoute: typeof FraudRoute
  LoginRoute: typeof LoginRoute
  NfcCardsRoute: typeof NfcCardsRoute
  PeopleRoute: typeof PeopleRoute
  PoliciesRoute: typeof PoliciesRoute
  PrescriptionsRoute: typeof PrescriptionsRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions': {
      id: '/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof PrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfc-cards': {
      id: '/nfc-cards'
      path: '/nfc-cards'
      fullPath: '/nfc-cards'
      preLoaderRoute: typeof NfcCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud': {
      id: '/fraud'
      path: '/fraud'
      fullPath: '/fraud'
      preLoaderRoute: typeof FraudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial': {
      id: '/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof FinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dids': {
      id: '/dids'
      path: '/dids'
      fullPath: '/dids'
      preLoaderRoute: typeof DidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/did-explorer': {
      id: '/did-explorer'
      path: '/did-explorer'
      fullPath: '/did-explorer'
      preLoaderRoute: typeof DidExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-timeline': {
      id: '/audit-timeline'
      path: '/audit-timeline'
      fullPath: '/audit-timeline'
      preLoaderRoute: typeof AuditTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  AuditTimelineRoute: AuditTimelineRoute,
  CommandRoute: CommandRoute,
  CredentialsRoute: CredentialsRoute,
  DidExplorerRoute: DidExplorerRoute,
  DidsRoute: DidsRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  FinancialRoute: FinancialRoute,
  FraudRoute: FraudRoute,
  LoginRoute: LoginRoute,
  NfcCardsRoute: NfcCardsRoute,
  PeopleRoute: PeopleRoute,
  PoliciesRoute: PoliciesRoute,
  PrescriptionsRoute: PrescriptionsRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
