/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StaffVerifyRouteImport } from './routes/staff.verify'
import { Route as StaffSignRouteImport } from './routes/staff.sign'
import { Route as StaffScheduleRouteImport } from './routes/staff.schedule'
import { Route as StaffProfileRouteImport } from './routes/staff.profile'
import { Route as StaffPatientsRouteImport } from './routes/staff.patients'
import { Route as PatientWalletRouteImport } from './routes/patient.wallet'
import { Route as PatientQrRouteImport } from './routes/patient.qr'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientInpatientRouteImport } from './routes/patient.inpatient'
import { Route as PatientHistoryRouteImport } from './routes/patient.history'
import { Route as PatientConsentRouteImport } from './routes/patient.consent'
import { Route as PatientBillingRouteImport } from './routes/patient.billing'
import { Route as PatientAppointmentsRouteImport } from './routes/patient.appointments'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPoliciesRouteImport } from './routes/admin.policies'
import { Route as AdminFraudRouteImport } from './routes/admin.fraud'
import { Route as AdminDidsRouteImport } from './routes/admin.dids'
import { Route as AdminComplianceRouteImport } from './routes/admin.compliance'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/patient/',
  path: '/patient/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffVerifyRoute = StaffVerifyRouteImport.update({
  id: '/staff/verify',
  path: '/staff/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSignRoute = StaffSignRouteImport.update({
  id: '/staff/sign',
  path: '/staff/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffScheduleRoute = StaffScheduleRouteImport.update({
  id: '/staff/schedule',
  path: '/staff/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffProfileRoute = StaffProfileRouteImport.update({
  id: '/staff/profile',
  path: '/staff/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffPatientsRoute = StaffPatientsRouteImport.update({
  id: '/staff/patients',
  path: '/staff/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientWalletRoute = PatientWalletRouteImport.update({
  id: '/patient/wallet',
  path: '/patient/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientQrRoute = PatientQrRouteImport.update({
  id: '/patient/qr',
  path: '/patient/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/patient/profile',
  path: '/patient/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientInpatientRoute = PatientInpatientRouteImport.update({
  id: '/patient/inpatient',
  path: '/patient/inpatient',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientHistoryRoute = PatientHistoryRouteImport.update({
  id: '/patient/history',
  path: '/patient/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientConsentRoute = PatientConsentRouteImport.update({
  id: '/patient/consent',
  path: '/patient/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientBillingRoute = PatientBillingRouteImport.update({
  id: '/patient/billing',
  path: '/patient/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/patient/appointments',
  path: '/patient/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPoliciesRoute = AdminPoliciesRouteImport.update({
  id: '/admin/policies',
  path: '/admin/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFraudRoute = AdminFraudRouteImport.update({
  id: '/admin/fraud',
  path: '/admin/fraud',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDidsRoute = AdminDidsRouteImport.update({
  id: '/admin/dids',
  path: '/admin/dids',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComplianceRoute = AdminComplianceRouteImport.update({
  id: '/admin/compliance',
  path: '/admin/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/dids': typeof AdminDidsRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/billing': typeof PatientBillingRoute
  '/patient/consent': typeof PatientConsentRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/inpatient': typeof PatientInpatientRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/qr': typeof PatientQrRoute
  '/patient/wallet': typeof PatientWalletRoute
  '/staff/patients': typeof StaffPatientsRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/schedule': typeof StaffScheduleRoute
  '/staff/sign': typeof StaffSignRoute
  '/staff/verify': typeof StaffVerifyRoute
  '/admin/': typeof AdminIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/dids': typeof AdminDidsRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/billing': typeof PatientBillingRoute
  '/patient/consent': typeof PatientConsentRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/inpatient': typeof PatientInpatientRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/qr': typeof PatientQrRoute
  '/patient/wallet': typeof PatientWalletRoute
  '/staff/patients': typeof StaffPatientsRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/schedule': typeof StaffScheduleRoute
  '/staff/sign': typeof StaffSignRoute
  '/staff/verify': typeof StaffVerifyRoute
  '/admin': typeof AdminIndexRoute
  '/patient': typeof PatientIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/dids': typeof AdminDidsRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/billing': typeof PatientBillingRoute
  '/patient/consent': typeof PatientConsentRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/inpatient': typeof PatientInpatientRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/qr': typeof PatientQrRoute
  '/patient/wallet': typeof PatientWalletRoute
  '/staff/patients': typeof StaffPatientsRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/schedule': typeof StaffScheduleRoute
  '/staff/sign': typeof StaffSignRoute
  '/staff/verify': typeof StaffVerifyRoute
  '/admin/': typeof AdminIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/audit'
    | '/admin/compliance'
    | '/admin/dids'
    | '/admin/fraud'
    | '/admin/policies'
    | '/admin/profile'
    | '/patient/appointments'
    | '/patient/billing'
    | '/patient/consent'
    | '/patient/history'
    | '/patient/inpatient'
    | '/patient/profile'
    | '/patient/qr'
    | '/patient/wallet'
    | '/staff/patients'
    | '/staff/profile'
    | '/staff/schedule'
    | '/staff/sign'
    | '/staff/verify'
    | '/admin/'
    | '/patient/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/audit'
    | '/admin/compliance'
    | '/admin/dids'
    | '/admin/fraud'
    | '/admin/policies'
    | '/admin/profile'
    | '/patient/appointments'
    | '/patient/billing'
    | '/patient/consent'
    | '/patient/history'
    | '/patient/inpatient'
    | '/patient/profile'
    | '/patient/qr'
    | '/patient/wallet'
    | '/staff/patients'
    | '/staff/profile'
    | '/staff/schedule'
    | '/staff/sign'
    | '/staff/verify'
    | '/admin'
    | '/patient'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/audit'
    | '/admin/compliance'
    | '/admin/dids'
    | '/admin/fraud'
    | '/admin/policies'
    | '/admin/profile'
    | '/patient/appointments'
    | '/patient/billing'
    | '/patient/consent'
    | '/patient/history'
    | '/patient/inpatient'
    | '/patient/profile'
    | '/patient/qr'
    | '/patient/wallet'
    | '/staff/patients'
    | '/staff/profile'
    | '/staff/schedule'
    | '/staff/sign'
    | '/staff/verify'
    | '/admin/'
    | '/patient/'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminComplianceRoute: typeof AdminComplianceRoute
  AdminDidsRoute: typeof AdminDidsRoute
  AdminFraudRoute: typeof AdminFraudRoute
  AdminPoliciesRoute: typeof AdminPoliciesRoute
  AdminProfileRoute: typeof AdminProfileRoute
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientBillingRoute: typeof PatientBillingRoute
  PatientConsentRoute: typeof PatientConsentRoute
  PatientHistoryRoute: typeof PatientHistoryRoute
  PatientInpatientRoute: typeof PatientInpatientRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientQrRoute: typeof PatientQrRoute
  PatientWalletRoute: typeof PatientWalletRoute
  StaffPatientsRoute: typeof StaffPatientsRoute
  StaffProfileRoute: typeof StaffProfileRoute
  StaffScheduleRoute: typeof StaffScheduleRoute
  StaffSignRoute: typeof StaffSignRoute
  StaffVerifyRoute: typeof StaffVerifyRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PatientIndexRoute: typeof PatientIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/patient'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/verify': {
      id: '/staff/verify'
      path: '/staff/verify'
      fullPath: '/staff/verify'
      preLoaderRoute: typeof StaffVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/sign': {
      id: '/staff/sign'
      path: '/staff/sign'
      fullPath: '/staff/sign'
      preLoaderRoute: typeof StaffSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/schedule': {
      id: '/staff/schedule'
      path: '/staff/schedule'
      fullPath: '/staff/schedule'
      preLoaderRoute: typeof StaffScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/profile': {
      id: '/staff/profile'
      path: '/staff/profile'
      fullPath: '/staff/profile'
      preLoaderRoute: typeof StaffProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/patients': {
      id: '/staff/patients'
      path: '/staff/patients'
      fullPath: '/staff/patients'
      preLoaderRoute: typeof StaffPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/wallet': {
      id: '/patient/wallet'
      path: '/patient/wallet'
      fullPath: '/patient/wallet'
      preLoaderRoute: typeof PatientWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/qr': {
      id: '/patient/qr'
      path: '/patient/qr'
      fullPath: '/patient/qr'
      preLoaderRoute: typeof PatientQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/patient/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/inpatient': {
      id: '/patient/inpatient'
      path: '/patient/inpatient'
      fullPath: '/patient/inpatient'
      preLoaderRoute: typeof PatientInpatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/history': {
      id: '/patient/history'
      path: '/patient/history'
      fullPath: '/patient/history'
      preLoaderRoute: typeof PatientHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/consent': {
      id: '/patient/consent'
      path: '/patient/consent'
      fullPath: '/patient/consent'
      preLoaderRoute: typeof PatientConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/billing': {
      id: '/patient/billing'
      path: '/patient/billing'
      fullPath: '/patient/billing'
      preLoaderRoute: typeof PatientBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/patient/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/policies': {
      id: '/admin/policies'
      path: '/admin/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AdminPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fraud': {
      id: '/admin/fraud'
      path: '/admin/fraud'
      fullPath: '/admin/fraud'
      preLoaderRoute: typeof AdminFraudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dids': {
      id: '/admin/dids'
      path: '/admin/dids'
      fullPath: '/admin/dids'
      preLoaderRoute: typeof AdminDidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/compliance': {
      id: '/admin/compliance'
      path: '/admin/compliance'
      fullPath: '/admin/compliance'
      preLoaderRoute: typeof AdminComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminComplianceRoute: AdminComplianceRoute,
  AdminDidsRoute: AdminDidsRoute,
  AdminFraudRoute: AdminFraudRoute,
  AdminPoliciesRoute: AdminPoliciesRoute,
  AdminProfileRoute: AdminProfileRoute,
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientBillingRoute: PatientBillingRoute,
  PatientConsentRoute: PatientConsentRoute,
  PatientHistoryRoute: PatientHistoryRoute,
  PatientInpatientRoute: PatientInpatientRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientQrRoute: PatientQrRoute,
  PatientWalletRoute: PatientWalletRoute,
  StaffPatientsRoute: StaffPatientsRoute,
  StaffProfileRoute: StaffProfileRoute,
  StaffScheduleRoute: StaffScheduleRoute,
  StaffSignRoute: StaffSignRoute,
  StaffVerifyRoute: StaffVerifyRoute,
  AdminIndexRoute: AdminIndexRoute,
  PatientIndexRoute: PatientIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
