/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DidExplorerRouteImport } from './routes/did-explorer'
import { Route as AuditTimelineRouteImport } from './routes/audit-timeline'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperIndexRouteImport } from './routes/super.index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SuperHospitalsRouteImport } from './routes/super.hospitals'
import { Route as StaffVisitorsRouteImport } from './routes/staff.visitors'
import { Route as StaffVerifyRouteImport } from './routes/staff.verify'
import { Route as StaffTrackerRouteImport } from './routes/staff.tracker'
import { Route as StaffSurgeriesRouteImport } from './routes/staff.surgeries'
import { Route as StaffSignRouteImport } from './routes/staff.sign'
import { Route as StaffScheduleRouteImport } from './routes/staff.schedule'
import { Route as StaffRoomsRouteImport } from './routes/staff.rooms'
import { Route as StaffProfileRouteImport } from './routes/staff.profile'
import { Route as StaffPrescriptionsRouteImport } from './routes/staff.prescriptions'
import { Route as StaffPatientsRouteImport } from './routes/staff.patients'
import { Route as StaffLabsRouteImport } from './routes/staff.labs'
import { Route as StaffEmergencyRouteImport } from './routes/staff.emergency'
import { Route as StaffCommandRouteImport } from './routes/staff.command'
import { Route as StaffCheckinRouteImport } from './routes/staff.checkin'
import { Route as StaffAttendanceRouteImport } from './routes/staff.attendance'
import { Route as StaffAppointmentsRouteImport } from './routes/staff.appointments'
import { Route as PatientZkproofRouteImport } from './routes/patient.zkproof'
import { Route as PatientWalletRouteImport } from './routes/patient.wallet'
import { Route as PatientVisitorsRouteImport } from './routes/patient.visitors'
import { Route as PatientVaccinesRouteImport } from './routes/patient.vaccines'
import { Route as PatientTelemedicineRouteImport } from './routes/patient.telemedicine'
import { Route as PatientRecordsRouteImport } from './routes/patient.records'
import { Route as PatientQrRouteImport } from './routes/patient.qr'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientInsuranceRouteImport } from './routes/patient.insurance'
import { Route as PatientInpatientRouteImport } from './routes/patient.inpatient'
import { Route as PatientHistoryRouteImport } from './routes/patient.history'
import { Route as PatientFamilyRouteImport } from './routes/patient.family'
import { Route as PatientEmergencyRouteImport } from './routes/patient.emergency'
import { Route as PatientConsentRouteImport } from './routes/patient.consent'
import { Route as PatientBillingRouteImport } from './routes/patient.billing'
import { Route as PatientAppointmentsRouteImport } from './routes/patient.appointments'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPrescriptionsRouteImport } from './routes/admin.prescriptions'
import { Route as AdminPoliciesRouteImport } from './routes/admin.policies'
import { Route as AdminPeopleRouteImport } from './routes/admin.people'
import { Route as AdminOnboardRouteImport } from './routes/admin.onboard'
import { Route as AdminNfcCardsRouteImport } from './routes/admin.nfc-cards'
import { Route as AdminFraudRouteImport } from './routes/admin.fraud'
import { Route as AdminFinancialRouteImport } from './routes/admin.financial'
import { Route as AdminDigitalTwinRouteImport } from './routes/admin.digital-twin'
import { Route as AdminDidsRouteImport } from './routes/admin.dids'
import { Route as AdminCommandRouteImport } from './routes/admin.command'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DidExplorerRoute = DidExplorerRouteImport.update({
  id: '/did-explorer',
  path: '/did-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditTimelineRoute = AuditTimelineRouteImport.update({
  id: '/audit-timeline',
  path: '/audit-timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperIndexRoute = SuperIndexRouteImport.update({
  id: '/super/',
  path: '/super/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/patient/',
  path: '/patient/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperHospitalsRoute = SuperHospitalsRouteImport.update({
  id: '/super/hospitals',
  path: '/super/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffVisitorsRoute = StaffVisitorsRouteImport.update({
  id: '/staff/visitors',
  path: '/staff/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffVerifyRoute = StaffVerifyRouteImport.update({
  id: '/staff/verify',
  path: '/staff/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffTrackerRoute = StaffTrackerRouteImport.update({
  id: '/staff/tracker',
  path: '/staff/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSurgeriesRoute = StaffSurgeriesRouteImport.update({
  id: '/staff/surgeries',
  path: '/staff/surgeries',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSignRoute = StaffSignRouteImport.update({
  id: '/staff/sign',
  path: '/staff/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffScheduleRoute = StaffScheduleRouteImport.update({
  id: '/staff/schedule',
  path: '/staff/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoomsRoute = StaffRoomsRouteImport.update({
  id: '/staff/rooms',
  path: '/staff/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffProfileRoute = StaffProfileRouteImport.update({
  id: '/staff/profile',
  path: '/staff/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffPrescriptionsRoute = StaffPrescriptionsRouteImport.update({
  id: '/staff/prescriptions',
  path: '/staff/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffPatientsRoute = StaffPatientsRouteImport.update({
  id: '/staff/patients',
  path: '/staff/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLabsRoute = StaffLabsRouteImport.update({
  id: '/staff/labs',
  path: '/staff/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffEmergencyRoute = StaffEmergencyRouteImport.update({
  id: '/staff/emergency',
  path: '/staff/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffCommandRoute = StaffCommandRouteImport.update({
  id: '/staff/command',
  path: '/staff/command',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffCheckinRoute = StaffCheckinRouteImport.update({
  id: '/staff/checkin',
  path: '/staff/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAttendanceRoute = StaffAttendanceRouteImport.update({
  id: '/staff/attendance',
  path: '/staff/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAppointmentsRoute = StaffAppointmentsRouteImport.update({
  id: '/staff/appointments',
  path: '/staff/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientZkproofRoute = PatientZkproofRouteImport.update({
  id: '/patient/zkproof',
  path: '/patient/zkproof',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientWalletRoute = PatientWalletRouteImport.update({
  id: '/patient/wallet',
  path: '/patient/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientVisitorsRoute = PatientVisitorsRouteImport.update({
  id: '/patient/visitors',
  path: '/patient/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientVaccinesRoute = PatientVaccinesRouteImport.update({
  id: '/patient/vaccines',
  path: '/patient/vaccines',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientTelemedicineRoute = PatientTelemedicineRouteImport.update({
  id: '/patient/telemedicine',
  path: '/patient/telemedicine',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRecordsRoute = PatientRecordsRouteImport.update({
  id: '/patient/records',
  path: '/patient/records',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientQrRoute = PatientQrRouteImport.update({
  id: '/patient/qr',
  path: '/patient/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/patient/profile',
  path: '/patient/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientInsuranceRoute = PatientInsuranceRouteImport.update({
  id: '/patient/insurance',
  path: '/patient/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientInpatientRoute = PatientInpatientRouteImport.update({
  id: '/patient/inpatient',
  path: '/patient/inpatient',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientHistoryRoute = PatientHistoryRouteImport.update({
  id: '/patient/history',
  path: '/patient/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientFamilyRoute = PatientFamilyRouteImport.update({
  id: '/patient/family',
  path: '/patient/family',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientEmergencyRoute = PatientEmergencyRouteImport.update({
  id: '/patient/emergency',
  path: '/patient/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientConsentRoute = PatientConsentRouteImport.update({
  id: '/patient/consent',
  path: '/patient/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientBillingRoute = PatientBillingRouteImport.update({
  id: '/patient/billing',
  path: '/patient/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/patient/appointments',
  path: '/patient/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPrescriptionsRoute = AdminPrescriptionsRouteImport.update({
  id: '/admin/prescriptions',
  path: '/admin/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPoliciesRoute = AdminPoliciesRouteImport.update({
  id: '/admin/policies',
  path: '/admin/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPeopleRoute = AdminPeopleRouteImport.update({
  id: '/admin/people',
  path: '/admin/people',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOnboardRoute = AdminOnboardRouteImport.update({
  id: '/admin/onboard',
  path: '/admin/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNfcCardsRoute = AdminNfcCardsRouteImport.update({
  id: '/admin/nfc-cards',
  path: '/admin/nfc-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFraudRoute = AdminFraudRouteImport.update({
  id: '/admin/fraud',
  path: '/admin/fraud',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinancialRoute = AdminFinancialRouteImport.update({
  id: '/admin/financial',
  path: '/admin/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDigitalTwinRoute = AdminDigitalTwinRouteImport.update({
  id: '/admin/digital-twin',
  path: '/admin/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDidsRoute = AdminDidsRouteImport.update({
  id: '/admin/dids',
  path: '/admin/dids',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommandRoute = AdminCommandRouteImport.update({
  id: '/admin/command',
  path: '/admin/command',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-timeline': typeof AuditTimelineRoute
  '/did-explorer': typeof DidExplorerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/command': typeof AdminCommandRoute
  '/admin/dids': typeof AdminDidsRoute
  '/admin/digital-twin': typeof AdminDigitalTwinRoute
  '/admin/financial': typeof AdminFinancialRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/nfc-cards': typeof AdminNfcCardsRoute
  '/admin/onboard': typeof AdminOnboardRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/prescriptions': typeof AdminPrescriptionsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/billing': typeof PatientBillingRoute
  '/patient/consent': typeof PatientConsentRoute
  '/patient/emergency': typeof PatientEmergencyRoute
  '/patient/family': typeof PatientFamilyRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/inpatient': typeof PatientInpatientRoute
  '/patient/insurance': typeof PatientInsuranceRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/qr': typeof PatientQrRoute
  '/patient/records': typeof PatientRecordsRoute
  '/patient/telemedicine': typeof PatientTelemedicineRoute
  '/patient/vaccines': typeof PatientVaccinesRoute
  '/patient/visitors': typeof PatientVisitorsRoute
  '/patient/wallet': typeof PatientWalletRoute
  '/patient/zkproof': typeof PatientZkproofRoute
  '/staff/appointments': typeof StaffAppointmentsRoute
  '/staff/attendance': typeof StaffAttendanceRoute
  '/staff/checkin': typeof StaffCheckinRoute
  '/staff/command': typeof StaffCommandRoute
  '/staff/emergency': typeof StaffEmergencyRoute
  '/staff/labs': typeof StaffLabsRoute
  '/staff/patients': typeof StaffPatientsRoute
  '/staff/prescriptions': typeof StaffPrescriptionsRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/rooms': typeof StaffRoomsRoute
  '/staff/schedule': typeof StaffScheduleRoute
  '/staff/sign': typeof StaffSignRoute
  '/staff/surgeries': typeof StaffSurgeriesRoute
  '/staff/tracker': typeof StaffTrackerRoute
  '/staff/verify': typeof StaffVerifyRoute
  '/staff/visitors': typeof StaffVisitorsRoute
  '/super/hospitals': typeof SuperHospitalsRoute
  '/admin/': typeof AdminIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/super/': typeof SuperIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-timeline': typeof AuditTimelineRoute
  '/did-explorer': typeof DidExplorerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/command': typeof AdminCommandRoute
  '/admin/dids': typeof AdminDidsRoute
  '/admin/digital-twin': typeof AdminDigitalTwinRoute
  '/admin/financial': typeof AdminFinancialRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/nfc-cards': typeof AdminNfcCardsRoute
  '/admin/onboard': typeof AdminOnboardRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/prescriptions': typeof AdminPrescriptionsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/billing': typeof PatientBillingRoute
  '/patient/consent': typeof PatientConsentRoute
  '/patient/emergency': typeof PatientEmergencyRoute
  '/patient/family': typeof PatientFamilyRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/inpatient': typeof PatientInpatientRoute
  '/patient/insurance': typeof PatientInsuranceRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/qr': typeof PatientQrRoute
  '/patient/records': typeof PatientRecordsRoute
  '/patient/telemedicine': typeof PatientTelemedicineRoute
  '/patient/vaccines': typeof PatientVaccinesRoute
  '/patient/visitors': typeof PatientVisitorsRoute
  '/patient/wallet': typeof PatientWalletRoute
  '/patient/zkproof': typeof PatientZkproofRoute
  '/staff/appointments': typeof StaffAppointmentsRoute
  '/staff/attendance': typeof StaffAttendanceRoute
  '/staff/checkin': typeof StaffCheckinRoute
  '/staff/command': typeof StaffCommandRoute
  '/staff/emergency': typeof StaffEmergencyRoute
  '/staff/labs': typeof StaffLabsRoute
  '/staff/patients': typeof StaffPatientsRoute
  '/staff/prescriptions': typeof StaffPrescriptionsRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/rooms': typeof StaffRoomsRoute
  '/staff/schedule': typeof StaffScheduleRoute
  '/staff/sign': typeof StaffSignRoute
  '/staff/surgeries': typeof StaffSurgeriesRoute
  '/staff/tracker': typeof StaffTrackerRoute
  '/staff/verify': typeof StaffVerifyRoute
  '/staff/visitors': typeof StaffVisitorsRoute
  '/super/hospitals': typeof SuperHospitalsRoute
  '/admin': typeof AdminIndexRoute
  '/patient': typeof PatientIndexRoute
  '/staff': typeof StaffIndexRoute
  '/super': typeof SuperIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-timeline': typeof AuditTimelineRoute
  '/did-explorer': typeof DidExplorerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/command': typeof AdminCommandRoute
  '/admin/dids': typeof AdminDidsRoute
  '/admin/digital-twin': typeof AdminDigitalTwinRoute
  '/admin/financial': typeof AdminFinancialRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/nfc-cards': typeof AdminNfcCardsRoute
  '/admin/onboard': typeof AdminOnboardRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/prescriptions': typeof AdminPrescriptionsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/billing': typeof PatientBillingRoute
  '/patient/consent': typeof PatientConsentRoute
  '/patient/emergency': typeof PatientEmergencyRoute
  '/patient/family': typeof PatientFamilyRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/inpatient': typeof PatientInpatientRoute
  '/patient/insurance': typeof PatientInsuranceRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/qr': typeof PatientQrRoute
  '/patient/records': typeof PatientRecordsRoute
  '/patient/telemedicine': typeof PatientTelemedicineRoute
  '/patient/vaccines': typeof PatientVaccinesRoute
  '/patient/visitors': typeof PatientVisitorsRoute
  '/patient/wallet': typeof PatientWalletRoute
  '/patient/zkproof': typeof PatientZkproofRoute
  '/staff/appointments': typeof StaffAppointmentsRoute
  '/staff/attendance': typeof StaffAttendanceRoute
  '/staff/checkin': typeof StaffCheckinRoute
  '/staff/command': typeof StaffCommandRoute
  '/staff/emergency': typeof StaffEmergencyRoute
  '/staff/labs': typeof StaffLabsRoute
  '/staff/patients': typeof StaffPatientsRoute
  '/staff/prescriptions': typeof StaffPrescriptionsRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/rooms': typeof StaffRoomsRoute
  '/staff/schedule': typeof StaffScheduleRoute
  '/staff/sign': typeof StaffSignRoute
  '/staff/surgeries': typeof StaffSurgeriesRoute
  '/staff/tracker': typeof StaffTrackerRoute
  '/staff/verify': typeof StaffVerifyRoute
  '/staff/visitors': typeof StaffVisitorsRoute
  '/super/hospitals': typeof SuperHospitalsRoute
  '/admin/': typeof AdminIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/super/': typeof SuperIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-timeline'
    | '/did-explorer'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/audit'
    | '/admin/command'
    | '/admin/dids'
    | '/admin/digital-twin'
    | '/admin/financial'
    | '/admin/fraud'
    | '/admin/nfc-cards'
    | '/admin/onboard'
    | '/admin/people'
    | '/admin/policies'
    | '/admin/prescriptions'
    | '/admin/profile'
    | '/patient/appointments'
    | '/patient/billing'
    | '/patient/consent'
    | '/patient/emergency'
    | '/patient/family'
    | '/patient/history'
    | '/patient/inpatient'
    | '/patient/insurance'
    | '/patient/profile'
    | '/patient/qr'
    | '/patient/records'
    | '/patient/telemedicine'
    | '/patient/vaccines'
    | '/patient/visitors'
    | '/patient/wallet'
    | '/patient/zkproof'
    | '/staff/appointments'
    | '/staff/attendance'
    | '/staff/checkin'
    | '/staff/command'
    | '/staff/emergency'
    | '/staff/labs'
    | '/staff/patients'
    | '/staff/prescriptions'
    | '/staff/profile'
    | '/staff/rooms'
    | '/staff/schedule'
    | '/staff/sign'
    | '/staff/surgeries'
    | '/staff/tracker'
    | '/staff/verify'
    | '/staff/visitors'
    | '/super/hospitals'
    | '/admin/'
    | '/patient/'
    | '/staff/'
    | '/super/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-timeline'
    | '/did-explorer'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/audit'
    | '/admin/command'
    | '/admin/dids'
    | '/admin/digital-twin'
    | '/admin/financial'
    | '/admin/fraud'
    | '/admin/nfc-cards'
    | '/admin/onboard'
    | '/admin/people'
    | '/admin/policies'
    | '/admin/prescriptions'
    | '/admin/profile'
    | '/patient/appointments'
    | '/patient/billing'
    | '/patient/consent'
    | '/patient/emergency'
    | '/patient/family'
    | '/patient/history'
    | '/patient/inpatient'
    | '/patient/insurance'
    | '/patient/profile'
    | '/patient/qr'
    | '/patient/records'
    | '/patient/telemedicine'
    | '/patient/vaccines'
    | '/patient/visitors'
    | '/patient/wallet'
    | '/patient/zkproof'
    | '/staff/appointments'
    | '/staff/attendance'
    | '/staff/checkin'
    | '/staff/command'
    | '/staff/emergency'
    | '/staff/labs'
    | '/staff/patients'
    | '/staff/prescriptions'
    | '/staff/profile'
    | '/staff/rooms'
    | '/staff/schedule'
    | '/staff/sign'
    | '/staff/surgeries'
    | '/staff/tracker'
    | '/staff/verify'
    | '/staff/visitors'
    | '/super/hospitals'
    | '/admin'
    | '/patient'
    | '/staff'
    | '/super'
  id:
    | '__root__'
    | '/'
    | '/audit-timeline'
    | '/did-explorer'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/audit'
    | '/admin/command'
    | '/admin/dids'
    | '/admin/digital-twin'
    | '/admin/financial'
    | '/admin/fraud'
    | '/admin/nfc-cards'
    | '/admin/onboard'
    | '/admin/people'
    | '/admin/policies'
    | '/admin/prescriptions'
    | '/admin/profile'
    | '/patient/appointments'
    | '/patient/billing'
    | '/patient/consent'
    | '/patient/emergency'
    | '/patient/family'
    | '/patient/history'
    | '/patient/inpatient'
    | '/patient/insurance'
    | '/patient/profile'
    | '/patient/qr'
    | '/patient/records'
    | '/patient/telemedicine'
    | '/patient/vaccines'
    | '/patient/visitors'
    | '/patient/wallet'
    | '/patient/zkproof'
    | '/staff/appointments'
    | '/staff/attendance'
    | '/staff/checkin'
    | '/staff/command'
    | '/staff/emergency'
    | '/staff/labs'
    | '/staff/patients'
    | '/staff/prescriptions'
    | '/staff/profile'
    | '/staff/rooms'
    | '/staff/schedule'
    | '/staff/sign'
    | '/staff/surgeries'
    | '/staff/tracker'
    | '/staff/verify'
    | '/staff/visitors'
    | '/super/hospitals'
    | '/admin/'
    | '/patient/'
    | '/staff/'
    | '/super/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditTimelineRoute: typeof AuditTimelineRoute
  DidExplorerRoute: typeof DidExplorerRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCommandRoute: typeof AdminCommandRoute
  AdminDidsRoute: typeof AdminDidsRoute
  AdminDigitalTwinRoute: typeof AdminDigitalTwinRoute
  AdminFinancialRoute: typeof AdminFinancialRoute
  AdminFraudRoute: typeof AdminFraudRoute
  AdminNfcCardsRoute: typeof AdminNfcCardsRoute
  AdminOnboardRoute: typeof AdminOnboardRoute
  AdminPeopleRoute: typeof AdminPeopleRoute
  AdminPoliciesRoute: typeof AdminPoliciesRoute
  AdminPrescriptionsRoute: typeof AdminPrescriptionsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientBillingRoute: typeof PatientBillingRoute
  PatientConsentRoute: typeof PatientConsentRoute
  PatientEmergencyRoute: typeof PatientEmergencyRoute
  PatientFamilyRoute: typeof PatientFamilyRoute
  PatientHistoryRoute: typeof PatientHistoryRoute
  PatientInpatientRoute: typeof PatientInpatientRoute
  PatientInsuranceRoute: typeof PatientInsuranceRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientQrRoute: typeof PatientQrRoute
  PatientRecordsRoute: typeof PatientRecordsRoute
  PatientTelemedicineRoute: typeof PatientTelemedicineRoute
  PatientVaccinesRoute: typeof PatientVaccinesRoute
  PatientVisitorsRoute: typeof PatientVisitorsRoute
  PatientWalletRoute: typeof PatientWalletRoute
  PatientZkproofRoute: typeof PatientZkproofRoute
  StaffAppointmentsRoute: typeof StaffAppointmentsRoute
  StaffAttendanceRoute: typeof StaffAttendanceRoute
  StaffCheckinRoute: typeof StaffCheckinRoute
  StaffCommandRoute: typeof StaffCommandRoute
  StaffEmergencyRoute: typeof StaffEmergencyRoute
  StaffLabsRoute: typeof StaffLabsRoute
  StaffPatientsRoute: typeof StaffPatientsRoute
  StaffPrescriptionsRoute: typeof StaffPrescriptionsRoute
  StaffProfileRoute: typeof StaffProfileRoute
  StaffRoomsRoute: typeof StaffRoomsRoute
  StaffScheduleRoute: typeof StaffScheduleRoute
  StaffSignRoute: typeof StaffSignRoute
  StaffSurgeriesRoute: typeof StaffSurgeriesRoute
  StaffTrackerRoute: typeof StaffTrackerRoute
  StaffVerifyRoute: typeof StaffVerifyRoute
  StaffVisitorsRoute: typeof StaffVisitorsRoute
  SuperHospitalsRoute: typeof SuperHospitalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PatientIndexRoute: typeof PatientIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  SuperIndexRoute: typeof SuperIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/did-explorer': {
      id: '/did-explorer'
      path: '/did-explorer'
      fullPath: '/did-explorer'
      preLoaderRoute: typeof DidExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-timeline': {
      id: '/audit-timeline'
      path: '/audit-timeline'
      fullPath: '/audit-timeline'
      preLoaderRoute: typeof AuditTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/': {
      id: '/super/'
      path: '/super'
      fullPath: '/super/'
      preLoaderRoute: typeof SuperIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/patient'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/hospitals': {
      id: '/super/hospitals'
      path: '/super/hospitals'
      fullPath: '/super/hospitals'
      preLoaderRoute: typeof SuperHospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/visitors': {
      id: '/staff/visitors'
      path: '/staff/visitors'
      fullPath: '/staff/visitors'
      preLoaderRoute: typeof StaffVisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/verify': {
      id: '/staff/verify'
      path: '/staff/verify'
      fullPath: '/staff/verify'
      preLoaderRoute: typeof StaffVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/tracker': {
      id: '/staff/tracker'
      path: '/staff/tracker'
      fullPath: '/staff/tracker'
      preLoaderRoute: typeof StaffTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/surgeries': {
      id: '/staff/surgeries'
      path: '/staff/surgeries'
      fullPath: '/staff/surgeries'
      preLoaderRoute: typeof StaffSurgeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/sign': {
      id: '/staff/sign'
      path: '/staff/sign'
      fullPath: '/staff/sign'
      preLoaderRoute: typeof StaffSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/schedule': {
      id: '/staff/schedule'
      path: '/staff/schedule'
      fullPath: '/staff/schedule'
      preLoaderRoute: typeof StaffScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/rooms': {
      id: '/staff/rooms'
      path: '/staff/rooms'
      fullPath: '/staff/rooms'
      preLoaderRoute: typeof StaffRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/profile': {
      id: '/staff/profile'
      path: '/staff/profile'
      fullPath: '/staff/profile'
      preLoaderRoute: typeof StaffProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/prescriptions': {
      id: '/staff/prescriptions'
      path: '/staff/prescriptions'
      fullPath: '/staff/prescriptions'
      preLoaderRoute: typeof StaffPrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/patients': {
      id: '/staff/patients'
      path: '/staff/patients'
      fullPath: '/staff/patients'
      preLoaderRoute: typeof StaffPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/labs': {
      id: '/staff/labs'
      path: '/staff/labs'
      fullPath: '/staff/labs'
      preLoaderRoute: typeof StaffLabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/emergency': {
      id: '/staff/emergency'
      path: '/staff/emergency'
      fullPath: '/staff/emergency'
      preLoaderRoute: typeof StaffEmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/command': {
      id: '/staff/command'
      path: '/staff/command'
      fullPath: '/staff/command'
      preLoaderRoute: typeof StaffCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/checkin': {
      id: '/staff/checkin'
      path: '/staff/checkin'
      fullPath: '/staff/checkin'
      preLoaderRoute: typeof StaffCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/attendance': {
      id: '/staff/attendance'
      path: '/staff/attendance'
      fullPath: '/staff/attendance'
      preLoaderRoute: typeof StaffAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/appointments': {
      id: '/staff/appointments'
      path: '/staff/appointments'
      fullPath: '/staff/appointments'
      preLoaderRoute: typeof StaffAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/zkproof': {
      id: '/patient/zkproof'
      path: '/patient/zkproof'
      fullPath: '/patient/zkproof'
      preLoaderRoute: typeof PatientZkproofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/wallet': {
      id: '/patient/wallet'
      path: '/patient/wallet'
      fullPath: '/patient/wallet'
      preLoaderRoute: typeof PatientWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/visitors': {
      id: '/patient/visitors'
      path: '/patient/visitors'
      fullPath: '/patient/visitors'
      preLoaderRoute: typeof PatientVisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/vaccines': {
      id: '/patient/vaccines'
      path: '/patient/vaccines'
      fullPath: '/patient/vaccines'
      preLoaderRoute: typeof PatientVaccinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/telemedicine': {
      id: '/patient/telemedicine'
      path: '/patient/telemedicine'
      fullPath: '/patient/telemedicine'
      preLoaderRoute: typeof PatientTelemedicineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/records': {
      id: '/patient/records'
      path: '/patient/records'
      fullPath: '/patient/records'
      preLoaderRoute: typeof PatientRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/qr': {
      id: '/patient/qr'
      path: '/patient/qr'
      fullPath: '/patient/qr'
      preLoaderRoute: typeof PatientQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/patient/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/insurance': {
      id: '/patient/insurance'
      path: '/patient/insurance'
      fullPath: '/patient/insurance'
      preLoaderRoute: typeof PatientInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/inpatient': {
      id: '/patient/inpatient'
      path: '/patient/inpatient'
      fullPath: '/patient/inpatient'
      preLoaderRoute: typeof PatientInpatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/history': {
      id: '/patient/history'
      path: '/patient/history'
      fullPath: '/patient/history'
      preLoaderRoute: typeof PatientHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/family': {
      id: '/patient/family'
      path: '/patient/family'
      fullPath: '/patient/family'
      preLoaderRoute: typeof PatientFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/emergency': {
      id: '/patient/emergency'
      path: '/patient/emergency'
      fullPath: '/patient/emergency'
      preLoaderRoute: typeof PatientEmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/consent': {
      id: '/patient/consent'
      path: '/patient/consent'
      fullPath: '/patient/consent'
      preLoaderRoute: typeof PatientConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/billing': {
      id: '/patient/billing'
      path: '/patient/billing'
      fullPath: '/patient/billing'
      preLoaderRoute: typeof PatientBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/patient/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/prescriptions': {
      id: '/admin/prescriptions'
      path: '/admin/prescriptions'
      fullPath: '/admin/prescriptions'
      preLoaderRoute: typeof AdminPrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/policies': {
      id: '/admin/policies'
      path: '/admin/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AdminPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/people': {
      id: '/admin/people'
      path: '/admin/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AdminPeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/onboard': {
      id: '/admin/onboard'
      path: '/admin/onboard'
      fullPath: '/admin/onboard'
      preLoaderRoute: typeof AdminOnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/nfc-cards': {
      id: '/admin/nfc-cards'
      path: '/admin/nfc-cards'
      fullPath: '/admin/nfc-cards'
      preLoaderRoute: typeof AdminNfcCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fraud': {
      id: '/admin/fraud'
      path: '/admin/fraud'
      fullPath: '/admin/fraud'
      preLoaderRoute: typeof AdminFraudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/financial': {
      id: '/admin/financial'
      path: '/admin/financial'
      fullPath: '/admin/financial'
      preLoaderRoute: typeof AdminFinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/digital-twin': {
      id: '/admin/digital-twin'
      path: '/admin/digital-twin'
      fullPath: '/admin/digital-twin'
      preLoaderRoute: typeof AdminDigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dids': {
      id: '/admin/dids'
      path: '/admin/dids'
      fullPath: '/admin/dids'
      preLoaderRoute: typeof AdminDidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/command': {
      id: '/admin/command'
      path: '/admin/command'
      fullPath: '/admin/command'
      preLoaderRoute: typeof AdminCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditTimelineRoute: AuditTimelineRoute,
  DidExplorerRoute: DidExplorerRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCommandRoute: AdminCommandRoute,
  AdminDidsRoute: AdminDidsRoute,
  AdminDigitalTwinRoute: AdminDigitalTwinRoute,
  AdminFinancialRoute: AdminFinancialRoute,
  AdminFraudRoute: AdminFraudRoute,
  AdminNfcCardsRoute: AdminNfcCardsRoute,
  AdminOnboardRoute: AdminOnboardRoute,
  AdminPeopleRoute: AdminPeopleRoute,
  AdminPoliciesRoute: AdminPoliciesRoute,
  AdminPrescriptionsRoute: AdminPrescriptionsRoute,
  AdminProfileRoute: AdminProfileRoute,
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientBillingRoute: PatientBillingRoute,
  PatientConsentRoute: PatientConsentRoute,
  PatientEmergencyRoute: PatientEmergencyRoute,
  PatientFamilyRoute: PatientFamilyRoute,
  PatientHistoryRoute: PatientHistoryRoute,
  PatientInpatientRoute: PatientInpatientRoute,
  PatientInsuranceRoute: PatientInsuranceRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientQrRoute: PatientQrRoute,
  PatientRecordsRoute: PatientRecordsRoute,
  PatientTelemedicineRoute: PatientTelemedicineRoute,
  PatientVaccinesRoute: PatientVaccinesRoute,
  PatientVisitorsRoute: PatientVisitorsRoute,
  PatientWalletRoute: PatientWalletRoute,
  PatientZkproofRoute: PatientZkproofRoute,
  StaffAppointmentsRoute: StaffAppointmentsRoute,
  StaffAttendanceRoute: StaffAttendanceRoute,
  StaffCheckinRoute: StaffCheckinRoute,
  StaffCommandRoute: StaffCommandRoute,
  StaffEmergencyRoute: StaffEmergencyRoute,
  StaffLabsRoute: StaffLabsRoute,
  StaffPatientsRoute: StaffPatientsRoute,
  StaffPrescriptionsRoute: StaffPrescriptionsRoute,
  StaffProfileRoute: StaffProfileRoute,
  StaffRoomsRoute: StaffRoomsRoute,
  StaffScheduleRoute: StaffScheduleRoute,
  StaffSignRoute: StaffSignRoute,
  StaffSurgeriesRoute: StaffSurgeriesRoute,
  StaffTrackerRoute: StaffTrackerRoute,
  StaffVerifyRoute: StaffVerifyRoute,
  StaffVisitorsRoute: StaffVisitorsRoute,
  SuperHospitalsRoute: SuperHospitalsRoute,
  AdminIndexRoute: AdminIndexRoute,
  PatientIndexRoute: PatientIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  SuperIndexRoute: SuperIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
